Ext.define("Pages.components.TemplateUtils.Base", {
  config: {
    controller: null
  },
  constructor: function(config) {
    this.initConfig(config);
    return this;
  },
  cutComment: function(text) {
    return text.split(/\r?\n/).filter(function(line) {
      return line.match(/^###.*$/) === null;
    }).join("\n");
  },
  cutEndRoot: function(text) {
    return text.split(/\r?\n/).filter(function(line) {
      return line.match(/^\s+\\$/) === null;
    }).join("\n");
  }
});

Ext.define("Pages.components.TemplateUtils.Simple", {
  extend: "Pages.components.TemplateUtils.Base",
  applyTemplate: function(templateTxt, data) {
    var result;
    result = {
      text: "",
      error: ""
    };
    console.log({
      templateTxt: templateTxt
    });
    templateTxt = this.cutComment(templateTxt);
    return new Promise(function(resolve, reject) {
      var e, i, len, ref, row, text, tmpl;
      try {
        text = [];
        tmpl = new Ext.Template(templateTxt);
        ref = data.rows;
        for (i = 0, len = ref.length; i < len; i++) {
          row = ref[i];
          text.push(tmpl.apply(row));
        }
        result.text = text.join("\n");
        console.log(JSON.stringify(result));
        return resolve(result);
      } catch (_error) {
        e = _error;
        result.error = e.toString();
        return reject(result);
      }
    });
  }
});

Ext.define("Pages.components.TemplateUtils.Underscore", {
  extend: "Pages.components.TemplateUtils.Base",
  applyTemplate: function(templateTxt, data) {
    var me, result;
    me = this;
    result = {
      text: "",
      error: ""
    };
    templateTxt = this.cutComment(templateTxt);
    return new Promise(function(resolve, reject) {
      var e, text, tmpl;
      try {
        tmpl = _.template(templateTxt);
        text = me.cutEndRoot(tmpl(data));
        result.text = text;
        return resolve(result);
      } catch (_error) {
        e = _error;
        result.error = e.toString();
        return reject(result);
      }
    });
  }
});

Ext.define("Pages.components.TemplateUtils.JavaScript", {
  extend: "Pages.components.TemplateUtils.Base",
  applyTemplate: function(templateTxt, data) {
    var result;
    result = {
      text: "",
      error: ""
    };
    templateTxt = this.cutComment(templateTxt);
    return new Promise(function(resolve, reject) {
      var e, func, text;
      try {
        func = "(function doTemplate(rows,cols) {\n" + templateTxt + "\n  return result\n})(data.rows,data.cols)";
        text = eval(func);
        if (Ext.isArray(text)) {
          result.text = text.join("\n");
          return resolve(result);
        }
      } catch (_error) {
        e = _error;
        result.error = e.toString();
        return reject(result);
      }
    });
  }
});

// ---
// generated by coffee-script 1.9.2